"""AI-powered funnel generation service from Figma designs"""

from typing import List, Optional, Dict, Any
from app.models.funnel_generation import (
    AutoGeneratedFunnel,
    GeneratedEvent,
    TrackedUIElement,
    FunnelStep,
    UIElementType
)
from app.integrations.figma_client import figma_client
from app.integrations.deepseek_client import deepseek_client
from app.core.logging import logger
from app.config import settings


class FunnelGenerationService:
    """
    Analyze Figma designs and auto-generate conversion funnels + tracking events
    
    Workflow:
    1. Analyze Figma file (all frames)
    2. AI identifies UI elements (buttons, forms, CTAs)
    3. Generate tracking events for each element
    4. Infer user flow from design structure
    5. Auto-create conversion funnel
    6. Generate SDK integration code
    """
    
    async def generate_funnel_from_figma(
        self,
        file_key: str,
        funnel_name: Optional[str] = None
    ) -> Dict[str, Any]:
        """
        Generate complete funnel from Figma design
        
        Args:
            file_key: Figma file key
            funnel_name: Optional custom funnel name
            
        Returns:
            Auto-generated funnel with events and implementation code
        """
        try:
            if settings.demo_mode or not settings.figma_access_token:
                return self._generate_demo_funnel()
            
            logger.info("Generating funnel from Figma", file_key=file_key)
            
            # Step 1: Get all frames from Figma
            frames = await figma_client.get_frames(file_key)
            
            logger.info(f"Analyzing {len(frames)} frames for funnel generation")
            
            # Step 2: Render frame screenshots
            frame_screenshots = []
            for frame in frames[:10]:  # Limit to first 10 frames
                image_bytes = await figma_client.render_frame_image(file_key, frame.id)
                frame_screenshots.append({
                    "frame": frame,
                    "screenshot": image_bytes
                })
            
            # Step 3: AI analysis to identify UI elements
            ui_elements = await self._ai_identify_ui_elements(frame_screenshots)
            
            # Step 4: Generate tracking events
            events = self._generate_events_from_elements(ui_elements)
            
            # Step 5: AI infers funnel flow
            funnel = await self._ai_generate_funnel_flow(
                frames=frames,
                events=events,
                funnel_name=funnel_name or "Auto-Generated Funnel"
            )
            
            # Step 6: Generate SDK code
            sdk_code = self._generate_sdk_code(events, funnel)
            
            # Step 7: Create implementation guide
            implementation_guide = self._create_implementation_guide(funnel, events)
            
            logger.info(
                "Funnel generated successfully",
                funnel_name=funnel.funnel_name,
                steps=len(funnel.steps),
                events=len(events)
            )
            
            return {
                "funnel": funnel,
                "events": events,
                "sdk_code": sdk_code,
                "implementation_guide": implementation_guide
            }
            
        except Exception as e:
            logger.error("Funnel generation failed", error=str(e))
            raise
    
    async def _ai_identify_ui_elements(
        self,
        frame_screenshots: List[Dict[str, Any]]
    ) -> List[TrackedUIElement]:
        """Use AI to identify trackable UI elements"""
        
        ui_elements = []
        
        for item in frame_screenshots:
            frame = item["frame"]
            screenshot = item["screenshot"]
            
            # AI prompt to identify UI elements
            prompt = f"""Analyze this UI design frame and identify all interactive elements that should be tracked for conversion optimization.

Frame: {frame.name}

For each interactive element, identify:
1. Element type (button, form, input, link, etc.)
2. Element purpose (what user action it represents)
3. Priority (1-10, how critical is this for conversion)
4. Suggested event name (snake_case)

Focus on:
- Primary CTAs (highest priority)
- Form inputs
- Navigation elements
- Important user actions

Return as JSON array of elements with: type, name, action_description, priority, suggested_event_name"""
            
            # Call DeepSeek Vision
            if settings.demo_mode:
                # Demo data
                elements_data = self._demo_ui_elements(frame.name)
            else:
                response = await deepseek_client.analyze_design(
                    screenshot,
                    frame.name,
                    issue_context=prompt
                )
                elements_data = response.get("elements", [])
            
            # Convert to TrackedUIElement
            for elem_data in elements_data:
                ui_elements.append(TrackedUIElement(
                    element_id=f"{frame.id}_{elem_data['suggested_event_name']}",
                    element_type=UIElementType(elem_data['type']),
                    element_name=elem_data['name'],
                    frame_name=frame.name,
                    action_description=elem_data['action_description'],
                    priority=elem_data['priority']
                ))
        
        return ui_elements
    
    def _generate_events_from_elements(
        self,
        ui_elements: List[TrackedUIElement]
    ) -> List[GeneratedEvent]:
        """Generate tracking events from UI elements"""
        
        events = []
        
        for element in ui_elements:
            # Generate event name
            event_name = self._element_to_event_name(element)
            
            # Determine category
            category = self._determine_event_category(element)
            
            # Generate event
            event = GeneratedEvent(
                event_name=event_name,
                event_category=category,
                description=f"{element.action_description} on {element.frame_name}",
                properties={
                    "frame": element.frame_name,
                    "element_type": element.element_type.value,
                    "priority": str(element.priority)
                },
                ui_element=element
            )
            
            events.append(event)
        
        return events
    
    async def _ai_generate_funnel_flow(
        self,
        frames: List[Any],
        events: List[GeneratedEvent],
        funnel_name: str
    ) -> AutoGeneratedFunnel:
        """Use AI to infer funnel flow from frames and events"""
        
        if settings.demo_mode:
            return self._demo_funnel(funnel_name)
        
        # AI prompt to infer funnel
        prompt = f"""Based on these UI frames and tracking events, infer the conversion funnel flow.

Frames: {[f.name for f in frames]}
Events: {[e.event_name for e in events]}

Determine:
1. Logical user flow order
2. Which events represent funnel steps
3. Expected conversion rates (if inferable)

Return JSON with: funnel_name, description, steps (ordered)"""
        
        # Call AI (would use DeepSeek chat model)
        # For now, use heuristic approach
        
        # Sort events by priority and frame order
        sorted_events = sorted(events, key=lambda e: (-e.ui_element.priority, e.ui_element.frame_name))
        
        # Create funnel steps
        steps = []
        for i, event in enumerate(sorted_events[:7], 1):  # Max 7 steps
            steps.append(FunnelStep(
                step_number=i,
                step_name=event.event_name,
                event_name=event.event_name,
                frame_name=event.ui_element.frame_name,
                description=event.description
            ))
        
        funnel = AutoGeneratedFunnel(
            funnel_name=funnel_name,
            description=f"Auto-generated funnel from Figma design",
            steps=steps,
            total_events=len(events),
            confidence=85.0
        )
        
        return funnel
    
    def _generate_sdk_code(
        self,
        events: List[GeneratedEvent],
        funnel: AutoGeneratedFunnel
    ) -> str:
        """Generate tracking SDK integration code"""
        
        code = f"""// Auto-generated tracking events for: {funnel.funnel_name}
// Generated by ArguxAI from Figma design

// Event definitions
const EVENTS = {{
"""
        
        for event in events:
            code += f"""  {event.event_name.upper()}: '{event.event_name}',\n"""
        
        code += """}

// Tracking functions
"""
        
        for event in events:
            code += f"""
export function track{self._to_pascal_case(event.event_name)}(properties = {{}}) {{
  analytics.track(EVENTS.{event.event_name.upper()}, {{
    ...properties,
    frame: '{event.ui_element.frame_name}',
    element_type: '{event.ui_element.element_type.value}',
    description: '{event.description}'
  }});
}}
"""
        
        return code
    
    def _create_implementation_guide(
        self,
        funnel: AutoGeneratedFunnel,
        events: List[GeneratedEvent]
    ) -> str:
        """Create implementation guide"""
        
        guide = f"""# {funnel.funnel_name} - Implementation Guide

## Overview
Auto-generated funnel with {len(funnel.steps)} steps and {len(events)} tracking events.

## Funnel Steps
"""
        
        for step in funnel.steps:
            guide += f"""
### Step {step.step_number}: {step.step_name}
- **Event**: `{step.event_name}`
- **Frame**: {step.frame_name}
- **Description**: {step.description}
"""
        
        guide += """
## Implementation Steps

1. **Add tracking SDK to your project**
```bash
npm install @arguxai/analytics
```

2. **Initialize SDK**
```javascript
import { Analytics } from '@arguxai/analytics';

const analytics = new Analytics({
  apiKey: 'your_arguxai_api_key',
  endpoint: 'https://api.arguxai.com/events'
});
```

3. **Add event tracking** (copy from generated SDK code file)

4. **Test events** using ArguxAI dashboard

5. **Start monitoring** - ArguxAI will automatically detect conversion drops!
"""
        
        return guide
    
    # Helper methods
    
    def _element_to_event_name(self, element: TrackedUIElement) -> str:
        """Convert UI element to event name"""
        action = "clicked" if element.element_type == UIElementType.BUTTON else "interacted"
        name = element.element_name.lower().replace(" ", "_").replace("-", "_")
        return f"{name}_{action}"
    
    def _determine_event_category(self, element: TrackedUIElement) -> str:
        """Determine event category"""
        if element.priority >= 8:
            return "conversion"
        elif element.element_type in [UIElementType.FORM, UIElementType.INPUT]:
            return "engagement"
        else:
            return "interaction"
    
    def _to_pascal_case(self, snake_str: str) -> str:
        """Convert snake_case to PascalCase"""
        return ''.join(word.capitalize() for word in snake_str.split('_'))
    
    def _demo_ui_elements(self, frame_name: str) -> List[Dict[str, Any]]:
        """Generate demo UI elements"""
        return [
            {
                "type": "button",
                "name": "Sign Up Button",
                "action_description": "Click to start signup",
                "priority": 10,
                "suggested_event_name": "signup_button_clicked"
            },
            {
                "type": "form",
                "name": "Email Input",
                "action_description": "Enter email address",
                "priority": 9,
                "suggested_event_name": "email_input_focused"
            }
        ]
    
    def _demo_funnel(self, funnel_name: str) -> AutoGeneratedFunnel:
        """Generate demo funnel"""
        return AutoGeneratedFunnel(
            funnel_name=funnel_name,
            description="Auto-generated signup funnel from Figma design",
            steps=[
                FunnelStep(
                    step_number=1,
                    step_name="landing_page_view",
                    event_name="page_viewed_landing",
                    frame_name="Landing Page",
                    description="User lands on homepage"
                ),
                FunnelStep(
                    step_number=2,
                    step_name="signup_button_click",
                    event_name="signup_button_clicked",
                    frame_name="Landing Page",
                    description="User clicks main CTA"
                ),
                FunnelStep(
                    step_number=3,
                    step_name="signup_form_start",
                    event_name="email_input_focused",
                    frame_name="Signup Form",
                    description="User starts filling form"
                ),
                FunnelStep(
                    step_number=4,
                    step_name="signup_form_submit",
                    event_name="signup_form_submitted",
                    frame_name="Signup Form",
                    description="User submits signup form"
                ),
                FunnelStep(
                    step_number=5,
                    step_name="otp_verification",
                    event_name="otp_input_focused",
                    frame_name="OTP Verification",
                    description="User enters OTP code"
                )
            ],
            total_events=12,
            confidence=88.5
        )
    
    def _generate_demo_funnel(self) -> Dict[str, Any]:
        """Generate complete demo funnel"""
        funnel = self._demo_funnel("User Signup Flow")
        
        events = [
            GeneratedEvent(
                event_name="signup_button_clicked",
                event_category="conversion",
                description="User clicked main signup CTA",
                properties={"frame": "Landing Page"},
                ui_element=TrackedUIElement(
                    element_id="landing_signup_btn",
                    element_type=UIElementType.BUTTON,
                    element_name="Get Started Button",
                    frame_name="Landing Page",
                    action_description="Click to start signup",
                    priority=10
                )
            )
        ]
        
        sdk_code = self._generate_sdk_code(events, funnel)
        implementation_guide = self._create_implementation_guide(funnel, events)
        
        return {
            "funnel": funnel,
            "events": events,
            "sdk_code": sdk_code,
            "implementation_guide": implementation_guide
        }


# Global service instance
funnel_generation_service = FunnelGenerationService()
