"""PR generation service orchestrating the fix workflow"""

from typing import List, Dict, Any
from datetime import datetime
from app.models.github import FileChange, PRMetadata, PRGenerationRequest, PRGenerationResponse, CodeLanguage
from app.models.issues import Issue
from app.integrations.github_client import github_client
from app.integrations.deepseek_client import deepseek_client
from app.services.issue_manager import issue_manager
from app.core.logging import logger
from app.config import settings


class PRGenerator:
    """
    Generate pull requests with AI-powered code fixes
    
    Workflow:
    1. Fetch diagnosed issue
    2. Get code context from GitHub
    3. Generate fix with DeepSeek
    4. Create feature branch
    5. Commit changes
    6. Create pull request
    7. Update issue with PR info
    """
    
    def _generate_branch_name(self, issue: Issue) -> str:
        """Generate branch name from issue"""
        funnel_step = issue.anomaly.funnel_step.replace("_", "-")
        timestamp = datetime.utcnow().strftime("%Y%m%d")
        return f"fix/{funnel_step}-{timestamp}"
    
    def _generate_pr_title(self, issue: Issue) -> str:
        """Generate PR title from diagnosis"""
        if issue.diagnosis:
            # Extract first sentence of root cause
            root_cause = issue.diagnosis.root_cause.split(".")[0]
            return f"Fix: {root_cause}"
        return f"Fix conversion drop in {issue.anomaly.funnel_step}"
    
    def _generate_pr_description(self, issue: Issue) -> str:
        """Generate comprehensive PR description"""
        
        desc = f"""## 🔍 Issue Detected

**Funnel Step**: {issue.anomaly.funnel_step}  
**Severity**: {issue.severity.value.upper()}  
**Drop**: {issue.anomaly.drop_percentage:.1f}% (from {issue.anomaly.baseline_conversion_rate:.1f}% to {issue.anomaly.current_conversion_rate:.1f}%)  
**Statistical Significance**: {issue.anomaly.sigma_value}σ

## 🤖 AI Diagnosis

**Root Cause**: {issue.diagnosis.root_cause if issue.diagnosis else 'N/A'}

**Confidence**: {issue.diagnosis.confidence if issue.diagnosis else 0}%

**Explanation**:  
{issue.diagnosis.explanation if issue.diagnosis else 'No diagnosis available'}

## 💡 Recommended Actions

"""
        
        if issue.diagnosis and issue.diagnosis.recommended_actions:
            for i, action in enumerate(issue.diagnosis.recommended_actions, 1):
                desc += f"{i}. {action}\n"
        
        desc += f"""
## 📊 Evidence

**Error Patterns**:
"""
        
        if issue.evidence.error_types:
            for error_type, count in list(issue.evidence.error_types.items())[:3]:
                desc += f"- `{error_type}`: {count} occurrences\n"
        
        desc += f"""
**Affected Segments**:
- Countries: {', '.join(issue.evidence.affected_countries[:3]) if issue.evidence.affected_countries else 'N/A'}
- Devices: {', '.join(issue.evidence.affected_devices[:2]) if issue.evidence.affected_devices else 'N/A'}

**Sessions Analyzed**: {issue.anomaly.current_sessions}

## 🏷️ Labels

`ai-generated` `conversion-fix` `{issue.severity.value}`

---

*This PR was automatically generated by [ArguxAI](https://github.com/your-org/arguxai)*
"""
        
        return desc
    
    def _generate_commit_message(self, issue: Issue) -> str:
        """Generate commit message"""
        return f"""fix({issue.anomaly.funnel_step}): {issue.diagnosis.root_cause if issue.diagnosis else 'conversion drop'}

Detected {issue.anomaly.drop_percentage:.1f}% drop in {issue.anomaly.funnel_step}.

AI diagnosis: {issue.diagnosis.explanation[:100] if issue.diagnosis else 'Manual investigation required'}...

Issue: {issue.id}
Severity: {issue.severity.value}
"""
    
    async def _detect_language(self, file_path: str) -> CodeLanguage:
        """Detect programming language from file extension"""
        ext_map = {
            ".py": CodeLanguage.PYTHON,
            ".js": CodeLanguage.JAVASCRIPT,
            ".ts": CodeLanguage.TYPESCRIPT,
            ".java": CodeLanguage.JAVA,
            ".go": CodeLanguage.GO,
            ".rb": CodeLanguage.RUBY
        }
        
        for ext, lang in ext_map.items():
            if file_path.endswith(ext):
                return lang
        
        return CodeLanguage.PYTHON  # Default
    
    async def generate_pr(
        self,
        issue_id: str,
        repository: str,
        target_files: List[str],
        base_branch: str = "main"
    ) -> PRGenerationResponse:
        """
        Generate pull request for an issue
        
        Args:
            issue_id: Issue ID to fix
            repository: GitHub repository (owner/repo)
            target_files: Files to modify
            base_branch: Base branch (default: main)
            
        Returns:
            PR generation response
        """
        try:
            # Get issue
            issue = issue_manager.get_issue(issue_id)
            if not issue:
                return PRGenerationResponse(
                    success=False,
                    message=f"Issue {issue_id} not found"
                )
            
            if not issue.diagnosis:
                return PRGenerationResponse(
                    success=False,
                    message="Issue must be diagnosed before generating PR"
                )
            
            logger.info(
                "Starting PR generation",
                issue_id=issue_id,
                repository=repository,
                target_files=target_files
            )
            
            # Demo mode: simulate PR creation
            if settings.demo_mode or not settings.github_token:
                logger.info("Demo mode: Simulating PR generation")
                
                branch_name = self._generate_branch_name(issue)
                pr_number = 123
                pr_url = f"https://github.com/{repository}/pull/{pr_number}"
                
                # Update issue
                await issue_manager.mark_fixed(
                    issue_id=issue_id,
                    commit_sha="demo_abc123",
                    pr_url=pr_url
                )
                
                return PRGenerationResponse(
                    success=True,
                    pr_url=pr_url,
                    pr_number=pr_number,
                    branch_name=branch_name,
                    commit_sha="demo_abc123",
                    files_changed=len(target_files),
                    message=f"PR simulated successfully (demo mode)"
                )
            
            # Real GitHub integration
            file_changes: List[FileChange] = []
            
            # Step 1: Fetch and fix each file
            for file_path in target_files:
                # Fetch original content
                original_content, file_sha = await github_client.get_file_content(
                    repo=repository,
                    file_path=file_path,
                    branch=base_branch
                )
                
                # Generate fix with AI
                fixed_content = await deepseek_client.generate_code_fix(
                    diagnosis=issue.diagnosis.model_dump(),
                    code_context=original_content,
                    language=await self._detect_language(file_path)
                )
                
# Add to changes
                file_changes.append(FileChange(
                    file_path=file_path,
                    original_content=original_content,
                    modified_content=fixed_content,
                    language=await self._detect_language(file_path)
                ))
            
            # Step 2: Create branch
            branch_name = self._generate_branch_name(issue)
            await github_client.create_branch(
                repo=repository,
                branch_name=branch_name,
                from_branch=base_branch
            )
            
            # Step 3: Commit changes
            commit_message = self._generate_commit_message(issue)
            commit_sha = await github_client.commit_changes(
                repo=repository,
                branch=branch_name,
                file_changes=file_changes,
                commit_message=commit_message
            )
            
            # Step 4: Create PR
            pr_metadata = PRMetadata(
                title=self._generate_pr_title(issue),
                description=self._generate_pr_description(issue),
                branch_name=branch_name,
                base_branch=base_branch,
                labels=["ai-generated", "conversion-fix", issue.severity.value]
            )
            
            pr_data = await github_client.create_pull_request(
                repo=repository,
                metadata=pr_metadata
            )
            
            # Step 5: Update issue
            await issue_manager.mark_fixed(
                issue_id=issue_id,
                commit_sha=commit_sha,
                pr_url=pr_data["url"]
            )
            
            logger.info(
                "PR generated successfully",
                issue_id=issue_id,
                pr_url=pr_data["url"],
                pr_number=pr_data["number"]
            )
            
            return PRGenerationResponse(
                success=True,
                pr_url=pr_data["url"],
                pr_number=pr_data["number"],
                branch_name=branch_name,
                commit_sha=commit_sha,
                files_changed=len(file_changes),
                message="PR created successfully"
            )
            
        except Exception as e:
            logger.error("PR generation failed", error=str(e), issue_id=issue_id)
            return PRGenerationResponse(
                success=False,
                message=f"PR generation failed: {str(e)}"
            )


# Global PR generator instance
pr_generator = PRGenerator()
