"""Funnel auto-generation API endpoints"""

from fastapi import APIRouter, HTTPException, status, Query
from typing import Optional
from app.models.funnel_generation import FunnelGenerationResponse, AutoGeneratedFunnel
from app.models.funnel_storage import (
    FunnelCreateRequest,
    FunnelUpdateRequest,
    FunnelListResponse,
    StoredFunnel
)
from app.services.funnel_generation_service import funnel_generation_service
from app.services.funnel_storage import funnel_storage
from app.core.dependencies import APIKeyDep
from app.core.logging import logger

router = APIRouter()


@router.post("/generate-from-figma", response_model=FunnelGenerationResponse)
async def generate_funnel_from_figma(
    file_key: str = Query(..., description="Figma file key"),
    funnel_name: Optional[str] = Query(None, description="Custom funnel name"),
    save: bool = Query(True, description="Save generated funnel"),
    api_key: APIKeyDep = None
) -> FunnelGenerationResponse:
    """
    🤖 **AI-Powered Autonomous Funnel Generation**
    
    Analyzes Figma design and automatically:
    1. Identifies all interactive UI elements (buttons, forms, inputs)
    2. Generates tracking events for each element
    3. Infers user flow from design structure
    4. Creates conversion funnel automatically
    5. Generates SDK integration code
    6. Provides implementation guide
    
    **After Generation**:
    - Review AI-generated funnel
    - Edit manually if needed (use PUT /api/funnel/{id})
    - Activate for monitoring (auto-enabled by default)
    """
    try:
        logger.info(
            "Generating funnel from Figma",
            file_key=file_key,
            funnel_name=funnel_name
        )
        
        # Generate funnel
        result = await funnel_generation_service.generate_funnel_from_figma(
            file_key=file_key,
            funnel_name=funnel_name
        )
        
        funnel: AutoGeneratedFunnel = result["funnel"]
        
        # Save if requested
        saved_funnel = None
        if save:
            saved_funnel = funnel_storage.save_ai_generated_funnel(funnel, file_key)
            logger.info(
                "Funnel saved",
                funnel_id=saved_funnel.id
            )
        
        logger.info(
            "Funnel generated successfully",
            funnel_name=funnel.funnel_name,
            steps=len(funnel.steps),
            events=funnel.total_events
        )
        
        return FunnelGenerationResponse(
            success=True,
            file_key=file_key,
            funnel=funnel,
            events=result["events"],
            sdk_code=result["sdk_code"],
            implementation_guide=result["implementation_guide"],
            message=f"Generated {funnel.funnel_name} with {len(funnel.steps)} steps. {'Saved and ready for monitoring!' if save else 'Not saved - set save=true to activate monitoring.'}"
        )
        
    except Exception as e:
        logger.error("Funnel generation failed", error=str(e))
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Funnel generation failed: {str(e)}"
        )


@router.get("/list", response_model=FunnelListResponse)
async def list_funnels(
    active_only: bool = Query(False, description="Show only active funnels"),
    api_key: APIKeyDep = None
) -> FunnelListResponse:
    """
    List all funnels
    
    **Returns**: All funnels (AI-generated and manual)
    
    **Example**:
    ```
    GET /api/funnel/list?active_only=true
    ```
    """
    try:
        funnels = funnel_storage.list_funnels(active_only=active_only)
        
        return FunnelListResponse(
            success=True,
            funnels=funnels,
            total=len(funnels),
            active=sum(1 for f in funnels if f.is_active)
        )
    except Exception as e:
        logger.error("Failed to list funnels", error=str(e))
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=str(e)
        )


@router.get("/{funnel_id}", response_model=StoredFunnel)
async def get_funnel(
    funnel_id: str,
    api_key: APIKeyDep = None
) -> StoredFunnel:
    """
    Get funnel details by ID
    
    **Example**:
    ```
    GET /api/funnel/funnel_signup_001
    ```
    """
    try:
        funnel = funnel_storage.get_funnel(funnel_id)
        
        if not funnel:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=f"Funnel {funnel_id} not found"
            )
        
        return funnel
        
    except HTTPException:
        raise
    except Exception as e:
        logger.error("Failed to get funnel", error=str(e))
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=str(e)
        )


@router.post("/create", response_model=StoredFunnel)
async def create_funnel_manually(
    request: FunnelCreateRequest,
    api_key: APIKeyDep = None
) -> StoredFunnel:
    """
    💡 **Manually Create Custom Funnel**
    
    Create funnel from scratch without Figma
    
    **Use Case**: Manual funnel creation when you already know your flow
    
    **Example Request**:
    ```json
    {
      "name": "Checkout Flow",
      "description": "Cart to payment complete",
      "steps": [
        {
          "step_number": 1,
          "step_name": "cart_view",
          "event_name": "cart_page_viewed"
        },
        {
          "step_number": 2,
          "step_name": "checkout_started",
          "event_name": "checkout_button_clicked"
        },
        {
          "step_number": 3,
          "step_name": "payment_complete",
          "event_name": "payment_success"
        }
      ]
    }
    ```
    
    **ArguxAI will monitor** this funnel automatically!
    """
    try:
        funnel = funnel_storage.create_funnel(request)
        
        logger.info(
            "Manual funnel created",
            funnel_id=funnel.id,
            name=funnel.name
        )
        
        return funnel
        
    except ValueError as e:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(e)
        )
    except Exception as e:
        logger.error("Failed to create funnel", error=str(e))
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=str(e)
        )


@router.put("/{funnel_id}", response_model=StoredFunnel)
async def update_funnel(
    funnel_id: str,
    request: FunnelUpdateRequest,
    api_key: APIKeyDep = None
) -> StoredFunnel:
    """
    ✏️ **Edit Funnel** (AI-generated or manual)
    
    Update funnel name, steps, or activation status
    
    **Use Cases**:
    - Refine AI-generated funnel
    - Add/remove steps
    - Rename steps
    - Deactivate/reactivate monitoring
    
    **Example**:
    ```
    PUT /api/funnel/funnel_signup_001
    {
      "name": "Updated Signup Flow",
      "steps": [...updated steps...],
      "is_active": true
    }
    ```
    
    **Note**: Editing AI-generated funnel marks it as "AI-Edited"
    """
    try:
        funnel = funnel_storage.update_funnel(funnel_id, request)
        
        return funnel
        
    except ValueError as e:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=str(e)
        )
    except Exception as e:
        logger.error("Failed to update funnel", error=str(e))
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=str(e)
        )


@router.delete("/{funnel_id}")
async def delete_funnel(
    funnel_id: str,
    api_key: APIKeyDep = None
):
    """
    🗑️ **Delete Funnel**
    
    Remove funnel from monitoring
    
    **Example**:
    ```
    DELETE /api/funnel/funnel_signup_001
    ```
    """
    try:
        success = funnel_storage.delete_funnel(funnel_id)
        
        if not success:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=f"Funnel {funnel_id} not found"
            )
        
        return {
            "success": True,
            "message": f"Funnel {funnel_id} deleted"
        }
        
    except HTTPException:
        raise
    except Exception as e:
        logger.error("Failed to delete funnel", error=str(e))
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=str(e)
        )


@router.post("/generate-from-figma", response_model=FunnelGenerationResponse)
async def generate_funnel_from_figma(
    file_key: str = Query(..., description="Figma file key"),
    funnel_name: Optional[str] = Query(None, description="Custom funnel name"),
    api_key: APIKeyDep = None
) -> FunnelGenerationResponse:
    """
    🤖 **AI-Powered Autonomous Funnel Generation**
    
    Analyzes Figma design and automatically:
    1. Identifies all interactive UI elements (buttons, forms, inputs)
    2. Generates tracking events for each element
    3. Infers user flow from design structure
    4. Creates conversion funnel automatically
    5. Generates SDK integration code
    6. Provides implementation guide
    
    **Workflow**:
    - DeepSeek Vision analyzes each Figma frame
    - AI identifies CTAs, forms, and interactive elements
    - Priority scoring (1-10) for each element
    - Auto-generates event names (e.g., `signup_button_clicked`)
    - Infers logical user flow order
    - Creates funnel steps with expected conversion rates
    - Generates ready-to-use JavaScript/TypeScript tracking code
    
    **Example**:
    ```
    POST /api/funnel/generate-from-figma?file_key=abc123&funnel_name=User%20Signup
    ```
    
    **Response Includes**:
    - Complete conversion funnel (steps, events)
    - All tracking events with properties
    - SDK integration code (copy-paste ready)
    - Step-by-step implementation guide
    
    **After Setup**:
    - ArguxAI automatically monitors all funnel steps
    - Detects conversion drops
    - Generates AI fixes
    - Creates Jira tickets
    - 100% autonomous! 🚀
    """
    try:
        logger.info(
            "Generating funnel from Figma",
            file_key=file_key,
            funnel_name=funnel_name
        )
        
        # Generate funnel
        result = await funnel_generation_service.generate_funnel_from_figma(
            file_key=file_key,
            funnel_name=funnel_name
        )
        
        funnel: AutoGeneratedFunnel = result["funnel"]
        
        logger.info(
            "Funnel generated successfully",
            funnel_name=funnel.funnel_name,
            steps=len(funnel.steps),
            events=funnel.total_events
        )
        
        return FunnelGenerationResponse(
            success=True,
            file_key=file_key,
            funnel=funnel,
            events=result["events"],
            sdk_code=result["sdk_code"],
            implementation_guide=result["implementation_guide"],
            message=f"Generated {funnel.funnel_name} with {len(funnel.steps)} steps and {funnel.total_events} events"
        )
        
    except Exception as e:
        logger.error("Funnel generation failed", error=str(e))
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Funnel generation failed: {str(e)}"
        )


@router.get("/demo")
async def get_demo_funnel(
    api_key: APIKeyDep = None
):
    """
    Get demo auto-generated funnel
    
    Shows example of what ArguxAI generates from Figma designs
    """
    try:
        result = await funnel_generation_service.generate_funnel_from_figma(
            file_key="demo",
            funnel_name="Demo Signup Flow"
        )
        
        return {
            "success": True,
            "funnel": result["funnel"],
            "events_sample": result["events"][:3],  # Show first 3 events
            "sdk_code_preview": result["sdk_code"][:500],  # First 500 chars
            "message": "This is what ArguxAI generates automatically from your Figma design!"
        }
        
    except Exception as e:
        logger.error("Demo funnel failed", error=str(e))
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=str(e)
        )
