"""Figma-to-Events models for automatic funnel generation"""

from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any
from enum import Enum


class UIElementType(str, Enum):
    """Types of UI elements that trigger events"""
    BUTTON = "button"
    FORM = "form"
    LINK = "link"
    INPUT = "input"
    CHECKBOX = "checkbox"
    RADIO = "radio"
    DROPDOWN = "dropdown"
    TAB = "tab"
    MODAL = "modal"


class TrackedUIElement(BaseModel):
    """UI element identified for tracking"""
    element_id: str = Field(..., description="Unique ID for this element")
    element_type: UIElementType
    element_name: str = Field(..., description="Human-readable name")
    frame_name: str = Field(..., description="Figma frame containing this element")
    action_description: str = Field(..., description="What user does (e.g., 'Click Sign Up')")
    priority: int = Field(..., description="Importance 1-10")
    coordinates: Optional[Dict[str, float]] = Field(None, description="x, y position")


class GeneratedEvent(BaseModel):
    """Auto-generated tracking event"""
    event_name: str = Field(..., description="Event name (e.g., 'signup_button_clicked')")
    event_category: str = Field(..., description="Category (e.g., 'engagement', 'conversion')")
    description: str = Field(..., description="What this event tracks")
    properties: Dict[str, str] = Field(default_factory=dict, description="Event properties")
    ui_element: TrackedUIElement
    
    class Config:
        json_schema_extra = {
            "example": {
                "event_name": "signup_button_clicked",
                "event_category": "conversion",
                "description": "User clicked the main sign-up CTA button",
                "properties": {
                    "button_text": "Get Started",
                    "button_color": "blue",
                    "location": "hero_section"
                },
                "ui_element": {
                    "element_type": "button",
                    "element_name": "Get Started Button",
                    "frame_name": "Landing Page"
                }
            }
        }


class FunnelStep(BaseModel):
    """Auto-generated funnel step"""
    step_number: int
    step_name: str = Field(..., description="Funnel step name")
    event_name: str = Field(..., description="Event that marks this step")
    frame_name: str = Field(..., description="Figma frame for this step")
    description: str = Field(..., description="What happens at this step")
    expected_conversion_rate: Optional[float] = Field(None, description="Expected % (if known)")


class AutoGeneratedFunnel(BaseModel):
    """Complete auto-generated conversion funnel"""
    funnel_name: str = Field(..., description="Funnel name (e.g., 'User Signup Flow')")
    description: str = Field(..., description="What this funnel tracks")
    steps: List[FunnelStep] = Field(..., description="Ordered funnel steps")
    total_events: int = Field(..., description="Total events generated")
    confidence: float = Field(..., description="AI confidence 0-100")
    
    class Config:
        json_schema_extra = {
            "example": {
                "funnel_name": "User Signup Flow",
                "description": "Complete signup journey from landing to verification",
                "steps": [
                    {
                        "step_number": 1,
                        "step_name": "landing_page_visit",
                        "event_name": "page_viewed_landing",
                        "frame_name": "Landing Page",
                        "description": "User lands on homepage"
                    },
                    {
                        "step_number": 2,
                        "step_name": "signup_form_started",
                        "event_name": "signup_form_focused",
                        "frame_name": "Signup Form",
                        "description": "User focuses on email input"
                    }
                ],
                "total_events": 12,
                "confidence": 87.5
            }
        }


class FunnelGenerationResponse(BaseModel):
    """Response from funnel auto-generation"""
    success: bool
    file_key: str
    funnel: Optional[AutoGeneratedFunnel] = None
    events: List[GeneratedEvent] = Field(default_factory=list)
    sdk_code: Optional[str] = Field(None, description="Generated tracking SDK code")
    implementation_guide: Optional[str] = Field(None, description="How to implement")
    message: str
